import type { Exercise } from '@/types';

export const EXERCISE_DB: Exercise[] = [
  // CHEST EXERCISES (35 + 15 new = 50)
  { id: 'c1', name: 'Barbell Bench Press', group: 'Chest', muscles: ['Pectorals', 'Triceps', 'Front Delts'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c2', name: 'Dumbbell Bench Press', group: 'Chest', muscles: ['Pectorals', 'Triceps', 'Front Delts'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c3', name: 'Incline Barbell Bench Press', group: 'Chest', muscles: ['Upper Chest', 'Triceps', 'Front Delts'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c4', name: 'Incline Dumbbell Bench Press', group: 'Chest', muscles: ['Upper Chest', 'Triceps', 'Front Delts'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c5', name: 'Decline Barbell Bench Press', group: 'Chest', muscles: ['Lower Chest', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c6', name: 'Decline Dumbbell Bench Press', group: 'Chest', muscles: ['Lower Chest', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c7', name: 'Dumbbell Flyes', group: 'Chest', muscles: ['Pectorals'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c8', name: 'Incline Dumbbell Flyes', group: 'Chest', muscles: ['Upper Chest'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c9', name: 'Cable Crossovers', group: 'Chest', muscles: ['Pectorals'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c10', name: 'Push-Up (Standard)', group: 'Chest', muscles: ['Pectorals', 'Triceps', 'Front Delts'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'c11', name: 'Push-Up (Wide)', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'c12', name: 'Push-Up (Diamond)', group: 'Chest', muscles: ['Triceps', 'Pectorals'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'c13', name: 'Push-Up (Decline)', group: 'Chest', muscles: ['Upper Chest', 'Triceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'c14', name: 'Push-Up (Incline)', group: 'Chest', muscles: ['Lower Chest', 'Triceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'c15', name: 'Push-Up (Archer)', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'c16', name: 'Push-Up (Pseudo Planche)', group: 'Chest', muscles: ['Pectorals', 'Front Delts', 'Triceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'c17', name: 'Dips (Chest Focus)', group: 'Chest', muscles: ['Pectorals', 'Triceps', 'Front Delts'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'c18', name: 'Weighted Dips', group: 'Chest', muscles: ['Pectorals', 'Triceps', 'Front Delts'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'c19', name: 'Machine Chest Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c20', name: 'Pec Deck Machine', group: 'Chest', muscles: ['Pectorals'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c21', name: 'Svend Press', group: 'Chest', muscles: ['Pectorals'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c22', name: 'Floor Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c23', name: 'Dumbbell Pullover', group: 'Chest', muscles: ['Pectorals', 'Lats'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c24', name: 'Landmine Press', group: 'Chest', muscles: ['Upper Chest', 'Front Delts'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c25', name: 'Single-Arm Dumbbell Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c26', name: 'Hammer Strength Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c27', name: 'Reverse-Grip Bench Press', group: 'Chest', muscles: ['Upper Chest', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c28', name: 'Close-Grip Bench Press', group: 'Chest', muscles: ['Triceps', 'Pectorals'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c29', name: 'Spoto Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c30', name: 'Board Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c31', name: 'Pin Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c32', name: 'Band-Resisted Push-Up', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'c33', name: 'Chain Bench Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c34', name: 'Feet-Up Bench Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c35', name: 'Guillotine Press', group: 'Chest', muscles: ['Upper Chest'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c36', name: 'Low Cable Crossover', group: 'Chest', muscles: ['Pectorals', 'Upper Chest'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c37', name: 'High Cable Crossover', group: 'Chest', muscles: ['Pectorals', 'Lower Chest'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c38', name: 'Dumbbell Floor Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c39', name: 'Barbell Floor Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c40', name: 'Cable Fly (Low to High)', group: 'Chest', muscles: ['Upper Chest'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c41', name: 'Cable Fly (High to Low)', group: 'Chest', muscles: ['Lower Chest'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c42', name: 'Incline Cable Fly', group: 'Chest', muscles: ['Upper Chest'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c43', name: 'Decline Cable Fly', group: 'Chest', muscles: ['Lower Chest'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c44', name: 'Plate Press', group: 'Chest', muscles: ['Pectorals'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c45', name: 'Smith Machine Bench Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c46', name: 'Smith Machine Incline Press', group: 'Chest', muscles: ['Upper Chest', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c47', name: 'Dumbbell Neutral Grip Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c48', name: 'Reverse-Grip Dumbbell Press', group: 'Chest', muscles: ['Upper Chest', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c49', name: 'Weighted Push-Up', group: 'Chest', muscles: ['Pectorals', 'Triceps', 'Front Delts'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'c50', name: 'Band Bench Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  // New chest exercises from provided list
  { id: 'c51', name: 'Incline Dumbbell Press', group: 'Chest', muscles: ['Upper Pectorals', 'Front Delts'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c52', name: 'Cable Crossover', group: 'Chest', muscles: ['Pectorals'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c53', name: 'Plate Press-Out', group: 'Chest', muscles: ['Pectorals'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c54', name: 'Machine Fly', group: 'Chest', muscles: ['Pectorals'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'c55', name: 'Seated Chest Press', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c56', name: 'Chest Dip Machine', group: 'Chest', muscles: ['Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c57', name: 'Standing Cable Press', group: 'Chest', muscles: ['Pectorals'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c58', name: 'Dumbbell Hex Press', group: 'Chest', muscles: ['Inner Pectorals', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'c59', name: 'Wide Grip Dip', group: 'Chest', muscles: ['Lower Pectorals', 'Triceps'], type: 'compound', isBodyweight: true, isTimed: false },

  // BACK EXERCISES (40 + 15 new = 55)
  { id: 'b1', name: 'Barbell Deadlift', group: 'Back', muscles: ['Lower Back', 'Lats', 'Traps', 'Glutes', 'Hamstrings'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b2', name: 'Sumo Deadlift', group: 'Back', muscles: ['Lower Back', 'Lats', 'Glutes', 'Quads'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b3', name: 'Romanian Deadlift', group: 'Back', muscles: ['Lower Back', 'Hamstrings', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b4', name: 'Stiff-Leg Deadlift', group: 'Back', muscles: ['Lower Back', 'Hamstrings'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b5', name: 'Deficit Deadlift', group: 'Back', muscles: ['Lower Back', 'Lats', 'Traps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b6', name: 'Rack Pull', group: 'Back', muscles: ['Lower Back', 'Traps', 'Lats'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b7', name: 'Barbell Row', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Traps', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b8', name: 'Pendlay Row', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Traps', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b9', name: 'Dumbbell Row', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Traps', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b10', name: 'T-Bar Row', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Traps', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b11', name: 'Chest-Supported Row', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Traps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b12', name: 'Seated Cable Row', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Traps', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b13', name: 'Lat Pulldown', group: 'Back', muscles: ['Lats', 'Biceps', 'Rhomboids'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b14', name: 'Close-Grip Lat Pulldown', group: 'Back', muscles: ['Lats', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b15', name: 'Wide-Grip Lat Pulldown', group: 'Back', muscles: ['Lats', 'Traps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b16', name: 'Behind-Neck Lat Pulldown', group: 'Back', muscles: ['Lats', 'Traps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b17', name: 'V-Bar Lat Pulldown', group: 'Back', muscles: ['Lats', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b18', name: 'Straight-Arm Lat Pulldown', group: 'Back', muscles: ['Lats'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b19', name: 'Pull-Up', group: 'Back', muscles: ['Lats', 'Biceps', 'Rhomboids'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'b20', name: 'Chin-Up', group: 'Back', muscles: ['Lats', 'Biceps', 'Rhomboids'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'b21', name: 'Wide-Grip Pull-Up', group: 'Back', muscles: ['Lats', 'Traps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'b22', name: 'Close-Grip Pull-Up', group: 'Back', muscles: ['Lats', 'Biceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'b23', name: 'Neutral-Grip Pull-Up', group: 'Back', muscles: ['Lats', 'Biceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'b24', name: 'Commando Pull-Up', group: 'Back', muscles: ['Lats', 'Biceps', 'Obliques'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'b25', name: 'Muscle-Up', group: 'Back', muscles: ['Lats', 'Biceps', 'Triceps', 'Chest'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'b26', name: 'Weighted Pull-Up', group: 'Back', muscles: ['Lats', 'Biceps', 'Rhomboids'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'b27', name: 'Shrug (Barbell)', group: 'Back', muscles: ['Traps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b28', name: 'Shrug (Dumbbell)', group: 'Back', muscles: ['Traps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b29', name: 'Face Pull', group: 'Back', muscles: ['Rear Delts', 'Rhomboids', 'Traps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b30', name: 'Reverse Fly (Dumbbell)', group: 'Back', muscles: ['Rear Delts', 'Rhomboids'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b31', name: 'Reverse Fly (Machine)', group: 'Back', muscles: ['Rear Delts', 'Rhomboids'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b32', name: 'Bent-Over Reverse Fly', group: 'Back', muscles: ['Rear Delts', 'Rhomboids'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b33', name: 'Good Morning', group: 'Back', muscles: ['Lower Back', 'Hamstrings'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b34', name: 'Hyperextension', group: 'Back', muscles: ['Lower Back', 'Glutes', 'Hamstrings'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'b35', name: 'Weighted Hyperextension', group: 'Back', muscles: ['Lower Back', 'Glutes', 'Hamstrings'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'b36', name: 'Back Extension', group: 'Back', muscles: ['Lower Back'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'b37', name: 'Superman', group: 'Back', muscles: ['Lower Back', 'Glutes'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'b38', name: 'Bird Dog', group: 'Back', muscles: ['Lower Back', 'Glutes'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'b39', name: 'Inverted Row', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Biceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'b40', name: 'Australian Pull-Up', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Biceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'b41', name: 'Meadows Row', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Traps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b42', name: 'Kroc Row', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Traps', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b43', name: 'Chest-Supported T-Bar Row', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Traps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b44', name: 'Seated Cable Row (Wide Grip)', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Traps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b45', name: 'Seated Cable Row (Close Grip)', group: 'Back', muscles: ['Lats', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b46', name: 'Single-Arm Lat Pulldown', group: 'Back', muscles: ['Lats', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b47', name: 'Single-Arm Cable Row', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b48', name: 'Trap Bar Deadlift', group: 'Back', muscles: ['Lower Back', 'Lats', 'Traps', 'Glutes', 'Quads'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b49', name: 'Snatch Grip Deadlift', group: 'Back', muscles: ['Lower Back', 'Lats', 'Traps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b50', name: 'Barbell Row (Underhand)', group: 'Back', muscles: ['Lats', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b51', name: 'Face Pull (Rope)', group: 'Back', muscles: ['Rear Delts', 'Rhomboids', 'Traps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b52', name: 'Reverse Fly (Cable)', group: 'Back', muscles: ['Rear Delts', 'Rhomboids'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b53', name: 'Snatch Grip High Pull', group: 'Back', muscles: ['Traps', 'Lats', 'Rear Delts'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b54', name: 'Rack Pull (Above Knees)', group: 'Back', muscles: ['Lower Back', 'Traps', 'Lats'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b55', name: 'Weighted Inverted Row', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Biceps'], type: 'compound', isBodyweight: true, isTimed: false },
  // New back exercises from provided list
  { id: 'b56', name: 'Machine Row', group: 'Back', muscles: ['Lats', 'Rhomboids'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b57', name: 'Pullover (Dumbbell)', group: 'Back', muscles: ['Lats', 'Pectorals'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b58', name: 'Reverse Grip Pulldown', group: 'Back', muscles: ['Lats', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b59', name: 'Cable Shrugs', group: 'Back', muscles: ['Traps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b60', name: 'Yates Row', group: 'Back', muscles: ['Lats', 'Lower Back'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b61', name: 'Ring Rows', group: 'Back', muscles: ['Lats', 'Rhomboids', 'Biceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'b62', name: 'Back Extension (Machine)', group: 'Back', muscles: ['Lower Back'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b63', name: 'Reverse Hyper', group: 'Back', muscles: ['Lower Back', 'Glutes', 'Hamstrings'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b64', name: 'Seal Row', group: 'Back', muscles: ['Lats', 'Rhomboids'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b65', name: 'Underhand Dumbbell Row', group: 'Back', muscles: ['Lats', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b66', name: 'Cable Pullover', group: 'Back', muscles: ['Lats'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b67', name: 'Banded Pull-Up', group: 'Back', muscles: ['Lats', 'Biceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'b68', name: 'Assisted Pull-Up Machine', group: 'Back', muscles: ['Lats', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'b69', name: 'Rope Pullover', group: 'Back', muscles: ['Lats'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'b70', name: 'Prone Incline Dumbbell Row', group: 'Back', muscles: ['Lats', 'Rhomboids'], type: 'compound', isBodyweight: false, isTimed: false },

  // LEGS EXERCISES (45 + 20 new = 65)
  { id: 'l1', name: 'Barbell Squat', group: 'Legs', muscles: ['Quads', 'Glutes', 'Lower Back'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l2', name: 'Front Squat', group: 'Legs', muscles: ['Quads', 'Glutes', 'Core'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l3', name: 'High-Bar Squat', group: 'Legs', muscles: ['Quads', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l4', name: 'Low-Bar Squat', group: 'Legs', muscles: ['Posterior Chain', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l5', name: 'Box Squat', group: 'Legs', muscles: ['Quads', 'Glutes', 'Hamstrings'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l6', name: 'Pause Squat', group: 'Legs', muscles: ['Quads', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l7', name: 'Tempo Squat', group: 'Legs', muscles: ['Quads', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l8', name: 'Safety Bar Squat', group: 'Legs', muscles: ['Quads', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l9', name: 'Zercher Squat', group: 'Legs', muscles: ['Quads', 'Glutes', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l10', name: 'Hack Squat', group: 'Legs', muscles: ['Quads', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l11', name: 'Leg Press', group: 'Legs', muscles: ['Quads', 'Glutes', 'Hamstrings'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l12', name: 'Single-Leg Press', group: 'Legs', muscles: ['Quads', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l13', name: 'Bulgarian Split Squat', group: 'Legs', muscles: ['Quads', 'Glutes', 'Hamstrings'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l14', name: 'Weighted Bulgarian Split Squat', group: 'Legs', muscles: ['Quads', 'Glutes', 'Hamstrings'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l15', name: 'Lunges (Walking)', group: 'Legs', muscles: ['Quads', 'Glutes', 'Hamstrings'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l16', name: 'Lunges (Stationary)', group: 'Legs', muscles: ['Quads', 'Glutes', 'Hamstrings'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l17', name: 'Reverse Lunge', group: 'Legs', muscles: ['Quads', 'Glutes', 'Hamstrings'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l18', name: 'Side Lunge', group: 'Legs', muscles: ['Quads', 'Glutes', 'Adductors'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l19', name: 'Curtsy Lunge', group: 'Legs', muscles: ['Glutes', 'Quads', 'Adductors'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l20', name: 'Step-Up', group: 'Legs', muscles: ['Quads', 'Glutes', 'Hamstrings'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l21', name: 'Weighted Step-Up', group: 'Legs', muscles: ['Quads', 'Glutes', 'Hamstrings'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l22', name: 'Goblet Squat', group: 'Legs', muscles: ['Quads', 'Glutes', 'Core'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l23', name: 'Dumbbell Squat', group: 'Legs', muscles: ['Quads', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l24', name: 'Pistol Squat', group: 'Legs', muscles: ['Quads', 'Glutes', 'Core'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l25', name: 'Assisted Pistol Squat', group: 'Legs', muscles: ['Quads', 'Glutes', 'Core'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l26', name: 'Shrimp Squat', group: 'Legs', muscles: ['Quads', 'Glutes', 'Core'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l27', name: 'Sissy Squat', group: 'Legs', muscles: ['Quads'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'l28', name: 'Leg Extension', group: 'Legs', muscles: ['Quads'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l29', name: 'Leg Curl (Lying)', group: 'Legs', muscles: ['Hamstrings'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l30', name: 'Leg Curl (Seated)', group: 'Legs', muscles: ['Hamstrings'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l31', name: 'Leg Curl (Standing)', group: 'Legs', muscles: ['Hamstrings'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l32', name: 'Nordic Curl', group: 'Legs', muscles: ['Hamstrings'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'l33', name: 'Glute-Ham Raise', group: 'Legs', muscles: ['Hamstrings', 'Glutes'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'l34', name: 'Romanian Deadlift (Dumbbell)', group: 'Legs', muscles: ['Hamstrings', 'Glutes', 'Lower Back'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l35', name: 'Single-Leg RDL', group: 'Legs', muscles: ['Hamstrings', 'Glutes', 'Lower Back'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l36', name: 'Weighted Single-Leg RDL', group: 'Legs', muscles: ['Hamstrings', 'Glutes', 'Lower Back'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l37', name: 'Hip Thrust', group: 'Legs', muscles: ['Glutes', 'Hamstrings'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l38', name: 'Barbell Hip Thrust', group: 'Legs', muscles: ['Glutes', 'Hamstrings'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l39', name: 'Single-Leg Hip Thrust', group: 'Legs', muscles: ['Glutes', 'Hamstrings'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l40', name: 'Glute Kickback', group: 'Legs', muscles: ['Glutes'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l41', name: 'Cable Pull-Through', group: 'Legs', muscles: ['Glutes', 'Hamstrings'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l42', name: 'Kettlebell Swing', group: 'Legs', muscles: ['Glutes', 'Hamstrings', 'Lower Back'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l43', name: 'Calf Raise (Standing)', group: 'Legs', muscles: ['Calves'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'l44', name: 'Calf Raise (Seated)', group: 'Legs', muscles: ['Calves'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l45', name: 'Donkey Calf Raise', group: 'Legs', muscles: ['Calves'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l46', name: 'Belt Squat', group: 'Legs', muscles: ['Quads', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l47', name: 'Sled Hack Squat', group: 'Legs', muscles: ['Quads', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l48', name: 'V-Squat Machine', group: 'Legs', muscles: ['Quads', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l49', name: 'Leg Press (High Foot)', group: 'Legs', muscles: ['Glutes', 'Hamstrings'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l50', name: 'Leg Press (Low Foot)', group: 'Legs', muscles: ['Quads'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l51', name: 'Hip Adduction Machine', group: 'Legs', muscles: ['Adductors'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l52', name: 'Hip Abduction Machine', group: 'Legs', muscles: ['Abductors', 'Glutes'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l53', name: 'Cable Hip Adduction', group: 'Legs', muscles: ['Adductors'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l54', name: 'Cable Hip Abduction', group: 'Legs', muscles: ['Abductors', 'Glutes'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l55', name: 'Single-Leg Lying Leg Curl', group: 'Legs', muscles: ['Hamstrings'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l56', name: 'Single-Leg Seated Leg Curl', group: 'Legs', muscles: ['Hamstrings'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l57', name: 'Glute Bridge (Barbell)', group: 'Legs', muscles: ['Glutes', 'Hamstrings'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l58', name: 'Reverse Hyperextension', group: 'Legs', muscles: ['Glutes', 'Hamstrings', 'Lower Back'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l59', name: '45-Degree Hyperextension (Weighted)', group: 'Legs', muscles: ['Lower Back', 'Glutes', 'Hamstrings'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'l60', name: 'Cossack Squat (Weighted)', group: 'Legs', muscles: ['Quads', 'Adductors', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l61', name: 'Weighted Pistol Squat', group: 'Legs', muscles: ['Quads', 'Glutes', 'Core'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l62', name: 'Bulgarian Split Squat (Barbell)', group: 'Legs', muscles: ['Quads', 'Glutes', 'Hamstrings'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l63', name: 'Smith Machine Squat', group: 'Legs', muscles: ['Quads', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l64', name: 'Safety Squat Bar Squat', group: 'Legs', muscles: ['Quads', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l65', name: 'Single-Leg Calf Raise (Weighted)', group: 'Legs', muscles: ['Calves'], type: 'isolation', isBodyweight: true, isTimed: false },
  // New legs exercises from provided list
  { id: 'l66', name: 'Barbell Lunges', group: 'Legs', muscles: ['Quads', 'Glutes', 'Hamstrings'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l67', name: 'Glute Bridge', group: 'Legs', muscles: ['Glutes'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l68', name: 'Box Jumps', group: 'Legs', muscles: ['Quads', 'Glutes', 'Calves'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'l69', name: 'Jefferson Squat', group: 'Legs', muscles: ['Quads', 'Glutes', 'Adductors'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l70', name: 'Calf Press on Leg Press', group: 'Legs', muscles: ['Calves'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'l71', name: 'Anderson Squat', group: 'Legs', muscles: ['Quads', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'l72', name: 'Toe Press', group: 'Legs', muscles: ['Calves'], type: 'isolation', isBodyweight: false, isTimed: false },

  // SHOULDERS EXERCISES (30 + 15 new = 45)
  { id: 's1', name: 'Overhead Press (Barbell)', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's2', name: 'Overhead Press (Dumbbell)', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's3', name: 'Push Press', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's4', name: 'Arnold Press', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's5', name: 'Seated Overhead Press', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's6', name: 'Landmine Press (Shoulder)', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's7', name: 'Z-Press', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts', 'Core'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's8', name: 'Handstand Push-Up', group: 'Shoulders', muscles: ['Front Delts', 'Triceps', 'Traps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 's9', name: 'Pike Push-Up', group: 'Shoulders', muscles: ['Front Delts', 'Triceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 's10', name: 'Wall Walk', group: 'Shoulders', muscles: ['Front Delts', 'Triceps', 'Core'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 's11', name: 'Lateral Raise (Dumbbell)', group: 'Shoulders', muscles: ['Side Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's12', name: 'Lateral Raise (Cable)', group: 'Shoulders', muscles: ['Side Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's13', name: 'Lateral Raise (Machine)', group: 'Shoulders', muscles: ['Side Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's14', name: 'Front Raise (Dumbbell)', group: 'Shoulders', muscles: ['Front Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's15', name: 'Front Raise (Cable)', group: 'Shoulders', muscles: ['Front Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's16', name: 'Front Raise (Plate)', group: 'Shoulders', muscles: ['Front Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's17', name: 'Rear Delt Fly (Dumbbell)', group: 'Shoulders', muscles: ['Rear Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's18', name: 'Rear Delt Fly (Cable)', group: 'Shoulders', muscles: ['Rear Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's19', name: 'Rear Delt Fly (Machine)', group: 'Shoulders', muscles: ['Rear Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's20', name: 'Upright Row (Barbell)', group: 'Shoulders', muscles: ['Side Delts', 'Traps', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's21', name: 'Upright Row (Dumbbell)', group: 'Shoulders', muscles: ['Side Delts', 'Traps', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's22', name: 'Upright Row (Cable)', group: 'Shoulders', muscles: ['Side Delts', 'Traps', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's23', name: 'Cuban Press', group: 'Shoulders', muscles: ['Side Delts', 'Rear Delts', 'Traps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's24', name: 'Around the World', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's25', name: 'Scaption', group: 'Shoulders', muscles: ['Side Delts', 'Front Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's26', name: 'Y-Raise', group: 'Shoulders', muscles: ['Rear Delts', 'Lower Traps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's27', name: 'T-Raise', group: 'Shoulders', muscles: ['Rear Delts', 'Middle Traps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's28', name: 'W-Raise', group: 'Shoulders', muscles: ['Rear Delts', 'Rotator Cuff'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's29', name: 'External Rotation (Dumbbell)', group: 'Shoulders', muscles: ['Rotator Cuff'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's30', name: 'External Rotation (Cable)', group: 'Shoulders', muscles: ['Rotator Cuff'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's31', name: 'Behind-the-Neck Press (Barbell)', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's32', name: 'Seated Dumbbell Press (Neutral)', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's33', name: 'Single-Arm Dumbbell Press', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's34', name: 'Lateral Raise (Leaning)', group: 'Shoulders', muscles: ['Side Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's35', name: 'Lateral Raise (Seated)', group: 'Shoulders', muscles: ['Side Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's36', name: 'Front Raise (Barbell)', group: 'Shoulders', muscles: ['Front Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's37', name: 'Rear Delt Row', group: 'Shoulders', muscles: ['Rear Delts', 'Rhomboids'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's38', name: 'Face Pull (External Rotation)', group: 'Shoulders', muscles: ['Rear Delts', 'Rotator Cuff'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's39', name: 'Prone Incline Dumbbell Rear Delt Fly', group: 'Shoulders', muscles: ['Rear Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's40', name: 'Dumbbell Shrug (Behind Back)', group: 'Shoulders', muscles: ['Traps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's41', name: 'Upright Row (EZ Bar)', group: 'Shoulders', muscles: ['Side Delts', 'Traps', 'Biceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's42', name: 'Cable Lateral Raise (Single Arm)', group: 'Shoulders', muscles: ['Side Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's43', name: 'Machine Lateral Raise', group: 'Shoulders', muscles: ['Side Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's44', name: 'Smith Machine Overhead Press', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's45', name: 'Landmine Single-Arm Press', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts'], type: 'compound', isBodyweight: false, isTimed: false },
  // New shoulders exercises from provided list
  { id: 's46', name: 'Face Pull', group: 'Shoulders', muscles: ['Rear Delts', 'Traps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's47', name: 'Machine Shoulder Press', group: 'Shoulders', muscles: ['Front Delts', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's48', name: 'Barbell Front Raise', group: 'Shoulders', muscles: ['Front Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's49', name: 'Machine Rear Delt Fly', group: 'Shoulders', muscles: ['Rear Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's50', name: 'Reverse Pec Deck', group: 'Shoulders', muscles: ['Rear Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's51', name: 'Clean and Press', group: 'Shoulders', muscles: ['Front Delts', 'Traps', 'Glutes'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's52', name: 'Bent Over Lateral Raise', group: 'Shoulders', muscles: ['Rear Delts'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's53', name: 'Bottoms-Up Kettlebell Press', group: 'Shoulders', muscles: ['Front Delts', 'Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's54', name: 'Bradford Press', group: 'Shoulders', muscles: ['Front Delts', 'Side Delts'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 's55', name: 'Trap Bar Shrug', group: 'Shoulders', muscles: ['Traps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's56', name: 'Band Pull-Apart', group: 'Shoulders', muscles: ['Rear Delts', 'Traps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's57', name: 'Y-T-W Raises', group: 'Shoulders', muscles: ['Rear Delts', 'Rotator Cuff'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's58', name: 'Cable Internal Rotation', group: 'Shoulders', muscles: ['Rotator Cuff'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 's59', name: 'Incline Y Raise', group: 'Shoulders', muscles: ['Rear Delts', 'Traps'], type: 'isolation', isBodyweight: false, isTimed: false },

  // ARMS EXERCISES (35 + 15 new = 50)
  { id: 'a1', name: 'Barbell Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a2', name: 'EZ Bar Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a3', name: 'Dumbbell Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a4', name: 'Hammer Curl', group: 'Arms', muscles: ['Brachialis', 'Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a5', name: 'Incline Dumbbell Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a6', name: 'Preacher Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a7', name: 'Spider Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a8', name: 'Concentration Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a9', name: 'Cable Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a10', name: 'Drag Curl', group: 'Arms', muscles: ['Biceps', 'Brachialis'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a11', name: '21s Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a12', name: 'Zottman Curl', group: 'Arms', muscles: ['Biceps', 'Brachialis'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a13', name: 'Waiter Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a14', name: 'Close-Grip Bench Press', group: 'Arms', muscles: ['Triceps', 'Chest'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'a15', name: 'Skull Crusher', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a16', name: 'Overhead Triceps Extension (Dumbbell)', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a17', name: 'Overhead Triceps Extension (Cable)', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a18', name: 'Triceps Pushdown', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a19', name: 'Triceps Kickback', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a20', name: 'Rope Pushdown', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a21', name: 'JM Press', group: 'Arms', muscles: ['Triceps'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'a22', name: 'Tate Press', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a23', name: 'Dips (Triceps Focus)', group: 'Arms', muscles: ['Triceps', 'Chest'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'a24', name: 'Bench Dip', group: 'Arms', muscles: ['Triceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'a25', name: 'Diamond Push-Up', group: 'Arms', muscles: ['Triceps', 'Chest'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'a26', name: 'Close-Grip Push-Up', group: 'Arms', muscles: ['Triceps', 'Chest'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'a27', name: 'Wrist Curl', group: 'Arms', muscles: ['Forearms'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a28', name: 'Reverse Wrist Curl', group: 'Arms', muscles: ['Forearms'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a29', name: 'Farmer Walk', group: 'Arms', muscles: ['Forearms', 'Grip'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'a30', name: 'Plate Pinch', group: 'Arms', muscles: ['Forearms', 'Grip'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a31', name: 'Towel Pull-Up', group: 'Arms', muscles: ['Forearms', 'Grip', 'Lats'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'a32', name: 'Fat Grip Curl', group: 'Arms', muscles: ['Forearms', 'Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a33', name: 'Reverse Curl', group: 'Arms', muscles: ['Brachioradialis', 'Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a34', name: 'Behind-Back Wrist Curl', group: 'Arms', muscles: ['Forearms'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a35', name: 'Gripper Training', group: 'Arms', muscles: ['Forearms', 'Grip'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a36', name: 'Incline Hammer Curl', group: 'Arms', muscles: ['Brachialis', 'Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a37', name: 'Cable Hammer Curl', group: 'Arms', muscles: ['Brachialis', 'Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a38', name: 'Reverse Grip Triceps Pushdown', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a39', name: 'Overhead Cable Triceps Extension (Rope)', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a40', name: 'Weighted Bench Dip', group: 'Arms', muscles: ['Triceps'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'a41', name: 'Close-Grip Bench Press (Smith)', group: 'Arms', muscles: ['Triceps', 'Chest'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'a42', name: 'Skull Crusher (EZ Bar)', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a43', name: 'Skull Crusher (Dumbbell)', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a44', name: 'Single-Arm Overhead Dumbbell Extension', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a45', name: 'Single-Arm Cable Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a46', name: 'Preacher Curl (Machine)', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a47', name: 'Spider Curl (Cable)', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a48', name: 'Bayesian Curl (Cable)', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a49', name: 'Wrist Curl (Barbell)', group: 'Arms', muscles: ['Forearms'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a50', name: 'Farmer Walk (Trap Bar)', group: 'Arms', muscles: ['Forearms', 'Grip'], type: 'compound', isBodyweight: false, isTimed: false },
  // New arms exercises from provided list
  { id: 'a51', name: 'Machine Preacher Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a52', name: 'French Press', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a53', name: 'Machine Tricep Extension', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a54', name: 'Machine Bicep Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a55', name: 'Cross Body Hammer Curl', group: 'Arms', muscles: ['Brachialis', 'Brachioradialis'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a56', name: 'V-Bar Pushdown', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a57', name: 'Lying Tricep Extension (EZ Bar)', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a58', name: 'Rope Hammer Curl', group: 'Arms', muscles: ['Brachialis', 'Brachioradialis'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a59', name: 'Band Tricep Pushdown', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a60', name: 'Bayesian Cable Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a61', name: 'Overhead Cable Curl', group: 'Arms', muscles: ['Biceps'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'a62', name: 'Pronated Grip Tricep Extension', group: 'Arms', muscles: ['Triceps'], type: 'isolation', isBodyweight: false, isTimed: false },

  // CORE EXERCISES (25 + 15 new = 40)
  { id: 'cr1', name: 'Crunch', group: 'Core', muscles: ['Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr2', name: 'Reverse Crunch', group: 'Core', muscles: ['Lower Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr3', name: 'Plank', group: 'Core', muscles: ['Abs', 'Lower Back'], type: 'isolation', isBodyweight: true, isTimed: true },
  { id: 'cr4', name: 'Side Plank', group: 'Core', muscles: ['Obliques', 'Abs'], type: 'isolation', isBodyweight: true, isTimed: true },
  { id: 'cr5', name: 'Hanging Leg Raise', group: 'Core', muscles: ['Lower Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr6', name: 'Lying Leg Raise', group: 'Core', muscles: ['Lower Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr7', name: 'Russian Twist', group: 'Core', muscles: ['Obliques', 'Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr8', name: 'Bicycle Crunch', group: 'Core', muscles: ['Abs', 'Obliques'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr9', name: 'Mountain Climber', group: 'Core', muscles: ['Abs', 'Hip Flexors'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr10', name: 'Dead Bug', group: 'Core', muscles: ['Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr11', name: 'Hollow Body Hold', group: 'Core', muscles: ['Abs'], type: 'isolation', isBodyweight: true, isTimed: true },
  { id: 'cr12', name: 'L-Sit', group: 'Core', muscles: ['Abs', 'Hip Flexors'], type: 'isolation', isBodyweight: true, isTimed: true },
  { id: 'cr13', name: 'Dragon Flag', group: 'Core', muscles: ['Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr14', name: 'Ab Wheel Rollout', group: 'Core', muscles: ['Abs', 'Lower Back'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'cr15', name: 'Cable Crunch', group: 'Core', muscles: ['Abs'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'cr16', name: 'Pallof Press', group: 'Core', muscles: ['Obliques', 'Abs'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'cr17', name: 'Woodchopper', group: 'Core', muscles: ['Obliques', 'Abs'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'cr18', name: 'Turkish Get-Up', group: 'Core', muscles: ['Abs', 'Obliques', 'Shoulders'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'cr19', name: 'Windshield Wiper', group: 'Core', muscles: ['Obliques', 'Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr20', name: 'Toes to Bar', group: 'Core', muscles: ['Lower Abs', 'Lats'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'cr21', name: 'Knees to Elbows', group: 'Core', muscles: ['Lower Abs', 'Lats'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'cr22', name: 'Flutter Kick', group: 'Core', muscles: ['Lower Abs', 'Hip Flexors'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr23', name: 'Scissor Kick', group: 'Core', muscles: ['Lower Abs', 'Hip Flexors'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr24', name: 'V-Up', group: 'Core', muscles: ['Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr25', name: 'Jackknife Sit-Up', group: 'Core', muscles: ['Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr26', name: 'Weighted Crunch', group: 'Core', muscles: ['Abs'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'cr27', name: 'Weighted Plank', group: 'Core', muscles: ['Abs', 'Lower Back'], type: 'isolation', isBodyweight: true, isTimed: true },
  { id: 'cr28', name: 'Cable Crunch (Rope)', group: 'Core', muscles: ['Abs'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'cr29', name: 'Cable Oblique Twist', group: 'Core', muscles: ['Obliques'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'cr30', name: 'Hanging Leg Raise (Weighted)', group: 'Core', muscles: ['Lower Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr31', name: 'Decline Bench Crunch (Weighted)', group: 'Core', muscles: ['Abs'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'cr32', name: 'Weighted Russian Twist', group: 'Core', muscles: ['Obliques', 'Abs'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'cr33', name: 'Pallof Press (Hold)', group: 'Core', muscles: ['Obliques', 'Abs'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'cr34', name: 'Landmine Twist', group: 'Core', muscles: ['Obliques', 'Abs'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'cr35', name: 'Dumbbell Side Bend', group: 'Core', muscles: ['Obliques'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'cr36', name: 'Plate Twist', group: 'Core', muscles: ['Obliques', 'Abs'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'cr37', name: 'Weighted Reverse Crunch', group: 'Core', muscles: ['Lower Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr38', name: 'Kneeling Cable Crunch', group: 'Core', muscles: ['Abs'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'cr39', name: 'Medicine Ball Slam', group: 'Core', muscles: ['Abs', 'Obliques'], type: 'compound', isBodyweight: false, isTimed: false },
  { id: 'cr40', name: 'Suitcase Carry', group: 'Core', muscles: ['Obliques', 'Abs', 'Forearms'], type: 'compound', isBodyweight: false, isTimed: false },
  // New core exercises from provided list
  { id: 'cr41', name: 'Decline Crunch', group: 'Core', muscles: ['Upper Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr42', name: 'Sit-Ups', group: 'Core', muscles: ['Abs', 'Hip Flexors'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'cr43', name: 'Hanging Knee Raise', group: 'Core', muscles: ['Lower Abs'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr44', name: 'Oblique Crunch', group: 'Core', muscles: ['Obliques'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr45', name: 'Front Lever', group: 'Core', muscles: ['Abs', 'Lats'], type: 'compound', isBodyweight: true, isTimed: true },
  { id: 'cr46', name: 'Bird Dog', group: 'Core', muscles: ['Lower Back', 'Glutes'], type: 'isolation', isBodyweight: true, isTimed: false },
  { id: 'cr47', name: 'Plank with Leg Lift', group: 'Core', muscles: ['Abs', 'Glutes'], type: 'isolation', isBodyweight: true, isTimed: true },
  { id: 'cr48', name: 'Swiss Ball Crunch', group: 'Core', muscles: ['Abs'], type: 'isolation', isBodyweight: false, isTimed: false },
  { id: 'cr49', name: 'Side Plank with Rotation', group: 'Core', muscles: ['Obliques', 'Abs'], type: 'isolation', isBodyweight: true, isTimed: true },
  { id: 'cr50', name: 'RKC Plank', group: 'Core', muscles: ['Abs', 'Glutes'], type: 'isolation', isBodyweight: true, isTimed: true },
  { id: 'cr51', name: 'Stir the Pot', group: 'Core', muscles: ['Abs', 'Obliques'], type: 'compound', isBodyweight: true, isTimed: false },
  { id: 'cr52', name: 'Kettlebell Windmill', group: 'Core', muscles: ['Obliques', 'Abs', 'Hamstrings'], type: 'compound', isBodyweight: false, isTimed: false }
];

export const getExerciseById = (id: string): Exercise | undefined => {
  return EXERCISE_DB.find(ex => ex.id === id);
};

export const getExercisesByGroup = (group: string): Exercise[] => {
  if (group === 'All') return EXERCISE_DB;
  return EXERCISE_DB.filter(ex => ex.group === group);
};

export const searchExercises = (query: string): Exercise[] => {
  const lowerQuery = query.toLowerCase();
  return EXERCISE_DB.filter(ex => 
    ex.name.toLowerCase().includes(lowerQuery) ||
    ex.muscles.some(m => m.toLowerCase().includes(lowerQuery))
  );
};